namespace CobbleCompendium.Server.Models.DTOs;

public record CobblemonDTO(
    bool implemented,
    int nationalPokedexNumber,
    string name,
    string primaryType,
    string secondaryType,
    float maleRatio,
    int height,
    int weight,
    string[] pokedex,
    string[] labels,
    string[] aspects,
    string[] abilities,
    string[] eggGroups,
    var baseStats,
    var evYield,
    int baseExperienceYield,
    string experienceGroup,
    int catchRate,
    int eggCycles,
    int baseFriendship,
    float baseScale,
    var hitbox,
    var behaviour,
    var drops,
    string[] moves,
    var evolutions,
);
